import type { GameListItem } from './types';

const steamPortraitThumbnailUrl = (gameId: number) =>
  `https://cdn.cloudflare.steamstatic.com/steam/apps/${gameId}/library_600x900.jpg`;

export const mockTopGames: GameListItem[] = [
  {
    gameId: 1245620,
    name: '엘든 링',
    genres: ['액션', 'RPG'],
    thumbnailUrl: steamPortraitThumbnailUrl(1245620),
    rating: 9.2,
  },
  {
    gameId: 2358720,
    name: '검은 신화: 오공',
    genres: ['RPG'],
    thumbnailUrl: steamPortraitThumbnailUrl(2358720),
    rating: 9.1,
  },
  {
    gameId: 2679460,
    name: '메타포: 리판타지오',
    genres: ['RPG', '전략'],
    thumbnailUrl: steamPortraitThumbnailUrl(2679460),
    rating: 9.3,
  },
  {
    gameId: 1845910,
    name: '드래곤 에이지: 베일가드',
    genres: ['RPG', '어드벤처'],
    thumbnailUrl: steamPortraitThumbnailUrl(1845910),
    rating: 8.8,
  },
  {
    gameId: 1086940,
    name: '발더스 게이트 3',
    genres: ['RPG'],
    thumbnailUrl: steamPortraitThumbnailUrl(1086940),
    rating: 9.4,
  },
  {
    gameId: 292030,
    name: '더 위쳐 3',
    genres: ['어드벤처', 'RPG'],
    thumbnailUrl: steamPortraitThumbnailUrl(292030),
    rating: 9.0,
  },
  {
    gameId: 1091500,
    name: '사이버펑크 2077',
    genres: ['RPG', '액션'],
    thumbnailUrl: steamPortraitThumbnailUrl(1091500),
    rating: 8.9,
  },
  {
    gameId: 582010,
    name: '몬스터 헌터: 월드',
    genres: ['액션', '어드벤처'],
    thumbnailUrl: steamPortraitThumbnailUrl(582010),
    rating: 8.8,
  },
  {
    gameId: 814380,
    name: '세키로: 섀도우 다이 트와이스',
    genres: ['액션', '어드벤처'],
    thumbnailUrl: steamPortraitThumbnailUrl(814380),
    rating: 9.0,
  },
  {
    gameId: 2050650,
    name: '바이오하자드 RE:4',
    genres: ['액션', '슈팅'],
    thumbnailUrl: steamPortraitThumbnailUrl(2050650),
    rating: 8.9,
  },
  {
    gameId: 553850,
    name: '헬다이버즈 2',
    genres: ['슈팅', '액션'],
    thumbnailUrl: steamPortraitThumbnailUrl(553850),
    rating: 8.7,
  },
  {
    gameId: 1623730,
    name: '팰월드',
    genres: ['어드벤처', '시뮬레이션'],
    thumbnailUrl: steamPortraitThumbnailUrl(1623730),
    rating: 8.3,
  },
  {
    gameId: 1145350,
    name: '하데스 2',
    genres: ['액션', '어드벤처'],
    thumbnailUrl: steamPortraitThumbnailUrl(1145350),
    rating: 8.9,
  },
  {
    gameId: 367520,
    name: '할로우 나이트',
    genres: ['어드벤처', '플랫폼'],
    thumbnailUrl: steamPortraitThumbnailUrl(367520),
    rating: 9.4,
  },
  {
    gameId: 1627720,
    name: 'P의 거짓',
    genres: ['액션', 'RPG'],
    thumbnailUrl: steamPortraitThumbnailUrl(1627720),
    rating: 8.6,
  },
  {
    gameId: 1868140,
    name: '데이브 더 다이버',
    genres: ['어드벤처', '시뮬레이션'],
    thumbnailUrl: steamPortraitThumbnailUrl(1868140),
    rating: 8.8,
  },
  {
    gameId: 646570,
    name: '슬레이 더 스파이어',
    genres: ['전략', '카드 / 보드'],
    thumbnailUrl: steamPortraitThumbnailUrl(646570),
    rating: 9.1,
  },
  {
    gameId: 2379780,
    name: '발라트로',
    genres: ['카드 / 보드', '전략'],
    thumbnailUrl: steamPortraitThumbnailUrl(2379780),
    rating: 9.2,
  },
  {
    gameId: 548430,
    name: '딥 락 갤럭틱',
    genres: ['슈팅', '액션'],
    thumbnailUrl: steamPortraitThumbnailUrl(548430),
    rating: 8.9,
  },
  {
    gameId: 105600,
    name: '테라리아',
    genres: ['어드벤처', '플랫폼'],
    thumbnailUrl: steamPortraitThumbnailUrl(105600),
    rating: 9.3,
  },
];
